backend:
  name: git-gateway
  branch: main
  identity_url: https://<your-site>.netlify.app/.netlify/identity
  gateway_url: https://<your-site>.netlify.app/.netlify/git

publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img"

site_url: https://<your-site>.netlify.app

logo_url: https://<your-site>.netlify.app/logo.png

# Control access
roles:
  - admin
  - editor

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }